/* eslint-disable camelcase */

exports.shorthands = undefined;

exports.up = pgm => {
  pgm.sql(`

    CREATE TABLE "account" (
      "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
      "name" varchar UNIQUE NOT NULL,
      "hash_password" varchar NOT NULL,
      "created_at" timestamp NOT NULL DEFAULT (now())
    );
    
    CREATE TABLE "note" (
      "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
      "title" varchar NOT NULL,
      "body" varchar,
      "account_id" integer NOT NULL,
      "created_at" timestamp NOT NULL DEFAULT (now()),
      "last_modified_at" timestamp NOT NULL DEFAULT (now())
    );
    
    CREATE TABLE "tag" (
      "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
      "name" varchar NOT NULL,
      "account_id" integer NOT NULL
    );
    
    CREATE TABLE "notetag" (
      "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
      "note_id" integer NOT NULL,
      "tag_id" integer NOT NULL
    );
    
    CREATE UNIQUE INDEX ON "account" ("name");
    
    CREATE INDEX ON "note" ("account_id");
    
    CREATE INDEX ON "tag" ("account_id");
    
    CREATE UNIQUE INDEX ON "tag" ("account_id", "name");
    
    ALTER TABLE "notetag" ADD FOREIGN KEY ("note_id") REFERENCES "note" ("id");
    
    ALTER TABLE "notetag" ADD FOREIGN KEY ("tag_id") REFERENCES "tag" ("id");
    
    ALTER TABLE "note" ADD FOREIGN KEY ("account_id") REFERENCES "account" ("id");
    
    ALTER TABLE "tag" ADD FOREIGN KEY ("account_id") REFERENCES "account" ("id");
    



    `);
};

exports.down = pgm => {
  pgm.sql(`
    DROP TABLE "notetag";
    DROP TABLE "tag";
    DROP TABLE "note";
    DROP TABLE "account";
    `)
};
