CREATE TABLE "account" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar UNIQUE NOT NULL,
  "hash_password" varchar NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "note" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "title" varchar NOT NULL,
  "body" varchar,
  "account_id" integer NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (now()),
  "last_modified_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "tag" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar UNIQUE NOT NULL
);

CREATE TABLE "notetag" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "note_id" integer NOT NULL,
  "tag_id" integer NOT NULL
);

ALTER TABLE "notetag" ADD FOREIGN KEY ("note_id") REFERENCES "note" ("id");

ALTER TABLE "notetag" ADD FOREIGN KEY ("tag_id") REFERENCES "tag" ("id");

ALTER TABLE "note" ADD FOREIGN KEY ("account_id") REFERENCES "account" ("id");
